#!/bin/bash

cd "$(dirname "${0}")"

go clean -i -x ./...

go get ./...
go install -v -x ./...
go fmt ./...
go vet -x ./...
go test -v -coverprofile=coverage.report ./...
go tool cover -func=coverage.report
